hotkeys:
  shell: {}
  profile: {}
ssh: {}
terminal:
  colorScheme:
    name: Solarized Dark
    foreground: '#708284'
    background: '#001e27'
    cursor: '#708284'
    colors:
      - '#002831'
      - '#d11c24'
      - '#738a05'
      - '#a57706'
      - '#2176c7'
      - '#c61c6f'
      - '#259286'
      - '#eae3cb'
      - '#001e27'
      - '#bd3613'
      - '#475b62'
      - '#536870'
      - '#708284'
      - '#5956ba'
      - '#819090'
      - '#fcf4dc'
  ligatures: true
  background: colorScheme
  environment: {}
  bell: audible
  rightClick: paste
  autoOpen: true
  bracketedPaste: true
  copyOnSelect: true
  font: DejaVu Sans Mono for Powerline
  scrollOnInput: false
appearance:
  theme: Compact
  vibrancy: true
  vibrancyType: fluent
  frame: thin
titleControl:
  prefix: ''
  removePattern: ''
  replacePattern: \sname
